services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - ./data:/app/backend/data
    
    ports:
      - 3039:8080
    environment:
      - 'OLLAMA_BASE_URL=http://host.docker.internal:11434'
      - 'WEBUI_SECRET_KEY='
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEBUI_AUTH=${WEBUI_AUTH}
      - SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS}
      - DO_NOT_TRACK=${DO_NOT_TRACK}
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY}
      - SEARXNG_QUERY_URL=${SEARXNG_QUERY_URL}
      - GOOGLE_PSE_API_KEY=${GOOGLE_PSE_API_KEY}
      - GOOGLE_PSE_ENGINE_ID=${GOOGLE_PSE_ENGINE_ID}
      - BRAVE_SEARCH_API_KEY=${BRAVE_SEARCH_API_KEY}
      - SERPER_API_KEY=${SERPER_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_ENVIRONMENT=${PINECONE_ENVIRONMENT}
      - PINECONE_INDEX=${PINECONE_INDEX}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME}
      - DATASTORE=${DATASTORE}
      - PROJECT_ID=${PROJECT_ID}
      - INDEX_NAME=${INDEX_NAME}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL}
      - LOCATION=${LOCATION}
      - REGION=${REGION}
      - CLAUDE_MODEL_NAME=${CLAUDE_MODEL_NAME}
      - VERTEXAI_PROJECT=${VERTEXAI_PROJECT}
      - VERTEXAI_LOCATION=${VERTEXAI_LOCATION}
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./ollama_data
  open-webui:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./open_webui_data
